controller_manager:
  ros__parameters:
    update_rate: 50

    # Actual controllers
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller_1:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_trajectory_controller_2:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_trajectory_controller_3:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_trajectory_controller_4:
      type: joint_trajectory_controller/JointTrajectoryController


joint_trajectory_controller_1:
  ros__parameters:
    # Must be same as URDF
    joints: ['fr_hip', 'fr_knee', 'fr_ankle']

    # Must be same as ros2_control.xacro
    command_interfaces: 
      - position
    state_interfaces:
      - position
      - velocity

joint_trajectory_controller_2:
  ros__parameters:
    # Must be same as URDF
    joints: ['fl_hip', 'fl_knee', 'fl_ankle']

    # Must be same as ros2_control.xacro
    command_interfaces: 
      - position
    state_interfaces:
      - position
      - velocity

joint_trajectory_controller_3:
  ros__parameters:
    # Must be same as URDF
    joints: ['bl_hip', 'bl_knee', 'bl_ankle']

    # Must be same as ros2_control.xacro
    command_interfaces: 
      - position
    state_interfaces:
      - position
      - velocity

joint_trajectory_controller_4:
  ros__parameters:
    # Must be same as URDF
    joints: ['br_hip', 'br_knee', 'br_ankle']

    # Must be same as ros2_control.xacro
    command_interfaces: 
      - position
    state_interfaces:
      - position
      - velocity
