# This message holds all data for controlling the ActionSteppy 
# leg gait node.
#
# Next requested direction
# Check if -1 or undefined
int8 direction

int8 ERROR2 =       -2
int8 ERROR1 =       -1
int8 IDLE =         0
int8 NORTH =        1
int8 NORTHWEST =    2 
int8 WEST =         3
int8 SOUTHWEST =    4
int8 SOUTH =        5
int8 SOUTHEAST =    6
int8 EAST =         7
int8 NORTHEAST =    8
int8 ROTCW =        100
int8 ROTCCW =       101

# Boolean for stopping gait
bool stop

# Anything else
